import { readFileSync, readdirSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';

/**
 * The Edge Functions run a vendored copy of the engine. A copy is only safe if
 * it can't drift, so these compare everything except the rewritten import lines
 * — an un-vendored rule change fails here rather than quietly giving remote
 * players a different game.
 */

const SRC = join(process.cwd(), 'src', 'lib');
const VENDOR = join(process.cwd(), 'supabase', 'functions', '_shared', 'vendor');

/** Import lines are expected to differ; nothing else may. */
function meaningfulLines(source: string): string[] {
	return source
		.split('\n')
		.filter((line) => !/^\s*(import|export)\b.*\bfrom\s+['"]/.test(line))
		.filter((line) => !line.startsWith('// GENERATED by scripts/vendor-engine.mjs'))
		.filter((line) => !line.startsWith('// Source: src/lib/'));
}

const expected = [
	'icons.ts',
	'game/types.ts',
	'game/engine.ts',
	'game/deck.ts',
	'game/rng.ts',
	...readdirSync(join(SRC, 'data'))
		.filter((f: string) => f.endsWith('.ts') && !f.endsWith('.test.ts'))
		.map((f: string) => `data/${f}`)
];

describe('vendored engine', () => {
	it('has been generated at all', () => {
		expect(existsSync(VENDOR), 'run `npm run vendor`').toBe(true);
	});

	it.each(expected)('%s matches the source it was copied from', (file) => {
		const vendored = join(VENDOR, file);
		expect(existsSync(vendored), `${file} is missing — run \`npm run vendor\``).toBe(true);

		const from = meaningfulLines(readFileSync(join(SRC, file), 'utf8'));
		const to = meaningfulLines(readFileSync(vendored, 'utf8')).filter((line) => line !== '');

		// The banner leaves a blank line; compare on non-empty content.
		expect(to).toEqual(from.filter((line) => line !== ''));
	});

	it('vendors every data pool, so a new category reaches remote play too', () => {
		const pools = readdirSync(join(SRC, 'data')).filter(
			(f: string) => f.endsWith('.ts') && !f.endsWith('.test.ts')
		);
		const vendoredPools = readdirSync(join(VENDOR, 'data')).filter((f: string) =>
			f.endsWith('.ts')
		);
		expect(vendoredPools.sort()).toEqual(pools.sort());
	});

	it('rewrote every import to something the edge runtime can resolve', () => {
		for (const file of expected) {
			const source = readFileSync(join(VENDOR, file), 'utf8');
			for (const [, spec] of source.matchAll(/\bfrom\s+['"]([^'"]+)['"]/g)) {
				// Bare npm/jsr specifiers are fine; relative ones must be explicit.
				if (!spec.startsWith('.')) continue;
				expect(spec, `${file} imports "${spec}" without an extension`).toMatch(/\.ts$/);
			}
			expect(source, `${file} still uses the $lib alias`).not.toContain("from '$lib");
		}
	});
});
