/**
 * Generates `src/lib/icons.ts` from Font Awesome Free's SVG source. Inlined
 * rather than the webfont (~1.4MB for fourteen glyphs) or a CDN stylesheet (a
 * third-party runtime request, which this build rules out).
 *
 * Run with: node scripts/extract-icons.mjs
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const SOLID = 'node_modules/@fortawesome/fontawesome-free/svgs/solid';
const OUT = 'src/lib/icons.ts';

/** Font Awesome slug -> the name we use in the app. */
const WANTED = [
	'basketball',
	'football',
	'baseball-bat-ball',
	'hockey-puck',
	'star',
	'tv',
	'couch',
	'gamepad',
	'user-group',
	'film',
	'pizza-slice',
	'glass-water',
	'wand-magic-sparkles',
	'umbrella-beach',
	'pen-to-square',
	'ice-cream',
	'cheese'
];

function extract(slug) {
	const svg = readFileSync(join(SOLID, `${slug}.svg`), 'utf8');
	const viewBox = svg.match(/viewBox="([^"]+)"/)?.[1];
	// The free solid icons are a single path each; bail loudly if that changes.
	const paths = [...svg.matchAll(/\sd="([^"]+)"/g)].map((m) => m[1]);
	if (!viewBox) throw new Error(`${slug}: no viewBox`);
	if (paths.length !== 1) throw new Error(`${slug}: expected 1 path, found ${paths.length}`);
	return { viewBox, path: paths[0] };
}

const entries = WANTED.map((slug) => [slug, extract(slug)]);

const body = entries
	.map(([slug, { viewBox, path }]) => {
		return `\t'${slug}': {\n\t\tviewBox: '${viewBox}',\n\t\tpath: '${path}'\n\t}`;
	})
	.join(',\n');

const file = `// GENERATED by scripts/extract-icons.mjs — edit that script, not this file.
//
// Font Awesome Free icon paths, inlined so the app makes no request for them.
// Icons are CC BY 4.0 (https://creativecommons.org/licenses/by/4.0/),
// (c) Fonticons, Inc. See the README's attribution note.

export interface IconDef {
\tviewBox: string;
\tpath: string;
}

export const ICONS = {
${body}
} as const satisfies Record<string, IconDef>;

export type IconName = keyof typeof ICONS;
`;

writeFileSync(OUT, file);
console.log(`wrote ${OUT} with ${entries.length} icons`);
