/**
 * Copies the game engine and content pools into `supabase/functions/_shared/vendor/`
 * with import specifiers rewritten to be fully explicit.
 *
 * Why this exists: the Supabase Edge Runtime resolves modules strictly. It will
 * not add a `.ts` extension, will not resolve a directory to `index.ts`, and does
 * not honour Deno's `sloppy-imports`. The app's own source uses extensionless
 * relative imports and the `$lib` alias, so importing it directly into a function
 * fails at boot with "Module not found" — which is proven, not theoretical.
 *
 * Rewriting the app's source instead was the alternative, but that would put
 * `.ts` extensions through every file in `src/lib` to satisfy a constraint that
 * belongs to one deploy target. Deriving a copy keeps the rulebook single-source:
 * `npm run test:unit` covers the original, and `vendor-engine.test.ts` fails if
 * this copy drifts from it.
 *
 * Run with: node scripts/vendor-engine.mjs
 */
import { readFileSync, writeFileSync, mkdirSync, readdirSync, rmSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join, relative, posix } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const SRC = join(root, 'src', 'lib');
const OUT = join(root, 'supabase', 'functions', '_shared', 'vendor');

/** Everything the server needs, and nothing that touches a browser. */
const FILES = [
	'icons.ts',
	'game/types.ts',
	'game/engine.ts',
	'game/deck.ts',
	'game/rng.ts',
	...readdirSync(join(SRC, 'data'))
		.filter((f) => f.endsWith('.ts') && !f.endsWith('.test.ts'))
		.map((f) => `data/${f}`)
];

/** `$lib/x` -> the vendored path it should point at, relative to the importer. */
function resolveAlias(spec, fromFile) {
	const bare = spec.slice('$lib/'.length);
	// A bare directory means its index file.
	const target = FILES.includes(`${bare}.ts`)
		? `${bare}.ts`
		: FILES.includes(`${bare}/index.ts`)
			? `${bare}/index.ts`
			: null;
	if (!target) throw new Error(`${fromFile}: cannot vendor import "${spec}"`);

	const fromDir = posix.dirname(fromFile);
	const rel = posix.relative(fromDir, target);
	return rel.startsWith('.') ? rel : `./${rel}`;
}

function rewrite(source, file) {
	// Covers `import ... from 'x'`, `export ... from 'x'` and `import type`.
	return source.replace(/(\bfrom\s+)(['"])([^'"]+)\2/g, (match, prefix, quote, spec) => {
		let next = spec;

		if (spec.startsWith('$lib/')) {
			next = resolveAlias(spec, file);
		} else if (spec.startsWith('./') || spec.startsWith('../')) {
			// Explicit extension, or a directory that needs its index.
			if (!/\.[a-z]+$/.test(spec)) {
				const fromDir = posix.dirname(file);
				const asFile = posix.normalize(posix.join(fromDir, `${spec}.ts`));
				next = FILES.includes(asFile) ? `${spec}.ts` : `${spec}/index.ts`;
			}
		} else {
			// Bare npm/jsr specifiers pass through untouched.
			return match;
		}

		return `${prefix}${quote}${next}${quote}`;
	});
}

rmSync(OUT, { recursive: true, force: true });

const banner = `// GENERATED by scripts/vendor-engine.mjs — do not edit.\n// Source: src/lib/%s. Run \`npm run vendor\` after changing the engine or pools.\n\n`;

for (const file of FILES) {
	const source = readFileSync(join(SRC, file), 'utf8');
	const out = join(OUT, file);
	mkdirSync(dirname(out), { recursive: true });
	writeFileSync(out, banner.replace('%s', file) + rewrite(source, file));
}

console.log(`vendored ${FILES.length} files into ${relative(root, OUT)}`);
